### ISSUE TITLE
error when compiling on linux

### ISSUE THREAD

**Issue by eebssk1** [ryohey/gmspack#2]
main.c: In function ‘main’:
main.c:113:18: warning: implicit declaration of function ‘getopt’ [-Wimplicit-function-declaration]
     while ((ch = getopt(argc, argv, "a:e:")) != -1) {
                  ^~~~~~
main.c:116:40: error: ‘optarg’ undeclared (first use in this function)
             fprintf(stdout, "%s %s\n", optarg, argv[1]);
                                        ^~~~~~
main.c:116:40: note: each undeclared identifier is reported only once for each function it appears in

compile using gcc 6.2
